#!/bin/bash
rsync -e ssh -avz 'oriole.home.lan:/etc/{dhcpd.conf,doas.conf,hostname.em0,hostname.em1,hostname.em2,hostname.em3,hosts,myname,ntpd.conf,pf.conf,rc.conf.local,resolv.conf,sysctl.conf,vnstat.conf,ssh/sshd_config}' etc/
rsync -e ssh -avz 'oriole.home.lan:/var/{unbound/etc/unbound.conf,nsd/etc/nsd.conf,nsd/zones/master/home.lan.zone,nsd/zones/master/192.168.1.zone}' var/
